[package]
name = "rust-rpxy"
version = "0.1.0"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/rust-rpxy"
repository = "https://github.com/junkurihara/rust-rpxy"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["std", "cargo", "wrap_help"] }
env_logger = "0.9.0"
futures = "0.3.21"
hyper = { version = "0.14.19", default-features = false, features = [
  "server",
  "http1",
  "http2",
  "stream",
] }
log = "0.4.17"
tokio = { version = "1.19.2", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
  "macros",
] }
tokio-rustls = { version = "0.23.4", features = ["early-data"] }
rustls-pemfile = { version = "1.0.0" }
rustls = "0.20.6"
rand = "0.8.5"
toml = "0.5.9"
rustc-hash = "1.1.0"
serde = { version = "1.0.137", features = ["derive"] }
hyper-rustls = { version = "0.23.0", default-features = false, features = [
  "tokio-runtime",
  "webpki-tokio",
  "http1",
  "http2",
] }
parking_lot = "0.12.1"
# hyper-trust-dns = { version = "0.4.2", default-features = false, features = [
#   "rustls-http2",
#   "dnssec-ring",
#   "dns-over-https-rustls",
#   "rustls-webpki",
#   "rustls-native",
#   "native-tls",
# ] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"


[dev-dependencies]


[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
