########################################
#                                      #
#       rust-rxpy configuration        #
#                                      #
########################################
###################################
#         Global settings         #
###################################
http_port = 8080
https_port = 8443

###################################
#         Backend settings        #
###################################

[[application]]
app_name = 'localhost' # this should be option, if null then same as hostname
hostname = 'localhost'
https_redirection = true
reverse_proxy = [
  { path = '*', destination = '192.168.10.0:3000', tls = true },
  { path = '/path/to', destination = '192.168.10.1:4000', tls = true },
]
## List of destinations to send data to.
## At this point, round-robin is used for load-balancing if multiple URLs are specified.
allowhosts = ['127.0.0.1', '::1', '192.168.10.0/24']
denyhosts = ['*']
tls_cert_path = 'localhost1.pem'
tls_cert_key_path = 'localhost1.pem'


[[application]]
app_name = 'locahost_application'
hostname = 'localhost.localdomain'
https_redirection = true
reverse_proxy = [{ path = '/', destination = 'www.google.com', tls = true }]
tls_cert_path = 'localhost2.pem'
tls_cert_key_path = 'localhost2.pem'
