########################################
#                                      #
#       rust-rxpy configuration        #
#                                      #
########################################
###################################
#         Global settings         #
###################################
# Both or either one of http/https ports must be specified
listen_port = 8080
listen_port_tls = 8443

# Optional
max_concurrent_streams = 128
max_clients = 512

# Optional: Listen [::]
listen_ipv6 = false

# Optional: App that serves all plaintext http request by referring to HOSTS or request header
# execpt for configured application.
# Note that this is only for http.
# Note that nothing is served for requests via https since secure channel cannot be
# established for unconfigured server_name, and they are always rejected by checking SNI.
default_app = 'another_localhost'

###################################
#         Backend settings        #
###################################
[application]

[apps.localhost]
server_name = 'localhost'
reverse_proxy = [
  # default destination if path is not specified
  # Array for load balancing
  { upstream = [
    { location = 'www.google.com', tls = true },
    { location = 'www.google.co.jp', tls = true },
  ], upstream_options = [
    "override_host",
  ] },
  { path = '/maps', upstream = [
    { location = 'www.bing.com', tls = true },
    { location = 'www.bing.co.jp', tls = true },
  ], upstream_options = [
    "override_host",
    "upgrade_insecure_requests",
  ] },
]
# Optional: TLS setting. if https_port is specified and tls is true above, this must be given.
tls = { https_redirection = true, tls_cert_path = '/certs/localhost.pem', tls_cert_key_path = '/certs/localhost.pem' } # for docker volume mounted certs
#tls = { https_redirection = true, tls_cert_path = './localhost.pem', tls_cert_key_path = './localhost.pem' }          # for local


## List of destinations to send data to.
## At this point, round-robin is used for load-balancing if multiple URLs are specified.
# allowhosts = ['127.0.0.1', '::1', '192.168.10.0/24'] # TODO
# denyhosts = ['*'] # TODO
[apps.another_localhost]
server_name = 'localhost.localdomain'
reverse_proxy = [{ upstream = [{ location = 'www.google.com', tls = true }] }]

###################################
#      Experimantal settings      #
###################################
[experimental]
h3 = true
