version: "3"
services:
  rpxy-rp:
    image: jqtype/rpxy
    container_name: rpxy
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
    build:
      context: ./
    environment:
      - DEBUG=true
    tty: false
    privileged: true
    volumes:
      - ./localhost.pem:/certs/localhost.pem:ro
      - ./config-example.toml:/etc/rpxy.toml:ro
