[package]
name = "rpxy-certs"
description = "Cert manager library for `rpxy`"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[features]

[dependencies]
rustc-hash = { version = "1.1.0" }
tracing = { version = "0.1.40" }
# anyhow = "1.0.86"
derive_builder = { version = "0.20.0" }
thiserror = { version = "1.0.61" }
# hot_reload = {version = "0.1.5"}
async-trait = { version = "0.1.80" }
# tokio-rustls = { version = "0.26.0", features = ["early-data"] }
rustls = { version = "0.23.8", default-features = false, features = [
  "aws_lc_rs",
] }
rustls-pemfile = { version = "2.1.2" }
rustls-webpki = { version = "0.102.4", default-features = false, features = [
  "std",
  "aws_lc_rs",
] }
x509-parser = { version = "0.16.0" }

[dev-dependencies]
tokio = { version = "1.37.0", default-features = false, features = [
  # "net",
  "rt-multi-thread",
  # "time",
  # "sync",
  "macros",
] }
