[package]
name = "rpxy-certs"
description = "Cert manager library for `rpxy`"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["http3"]
http3 = []

[dependencies]
rustc-hash = { version = "2.0.0" }
tracing = { version = "0.1.40" }
derive_builder = { version = "0.20.0" }
thiserror = { version = "1.0.63" }
hot_reload = { version = "0.1.6" }
async-trait = { version = "0.1.81" }
rustls = { version = "0.23.12", default-features = false, features = [
  "std",
  "aws_lc_rs",
] }
rustls-pemfile = { version = "2.1.2" }
rustls-webpki = { version = "0.102.6", default-features = false, features = [
  "std",
  "aws_lc_rs",
] }
x509-parser = { version = "0.16.0" }

[dev-dependencies]
tokio = { version = "1.39.1", default-features = false, features = [
  "rt-multi-thread",
  "macros",
] }
