version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST="127.0.0.1"
      - VIRTUAL_PORT=80
    expose:
      - 80
    ports:
      - 127.0.0.1:8888:80
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx-rp:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy-nginx
    ports:
      - 127.0.0.1:8090:80
    restart: always
    tty: false
    privileged: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  caddy-rp:
    image: caddy:2
    container_name: proxy-caddy
    ports:
      - 127.0.0.1:8100:80
    restart: unless-stopped
    tty: false
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
