listen_port = 8080
# listen_port_tls = 8443
listen_ipv6 = false

max_concurrent_streams = 128
max_clients = 512

default_app = 'localhost' # passing through 127.0.0.1

[apps]

[apps.localhost]
server_name = 'localhost'
reverse_proxy = [
  # default destination if path is not specified
  # Array for load balancing
  { upstream = [{ location = 'backend-nginx', tls = false }] },
  # { upstream = [{ location = '192.168.100.100', tls = false }] },
]
