name: Build and Publish Docker x86_64

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rpxy

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: GitHub Environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release build and push
        if: ${{ env.BRANCH == 'main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          file: ./docker/Dockerfile
          platforms: linux/amd64

      - name: Release build and push x86_64-slim
        if: ${{ env.BRANCH == 'main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:slim, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest-slim
          file: ./docker/Dockerfile.amd64-slim
          platforms: linux/amd64

      - name: Nightly build and push
        if: ${{ env.BRANCH == 'develop' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:nightly
          file: ./docker/Dockerfile
          platforms: linux/amd64
